
name: macOS debug
on:
  push:
    paths:
      - "acrh17.config"
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
